[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_incomplete_defs = false
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "drivers.rest.*"
disallow_incomplete_defs = false
disallow_untyped_defs = false
disallow_untyped_decorators = false
disallow_subclassing_any = false

[[tool.mypy.overrides]]
module = [
    "flask_restful",
    "flask_apispec",
    "flask_apispec.extension",
    "flask_apispec.views"
]
ignore_missing_imports = true
